spring:
  application:
    name: address-reactive-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/address
  elasticsearch:
    hosts: localhost:9200
    cluster-name: docker-cluster
    rest:
      uris: http://localhost:9200

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    enabled-by-default: false #desabilita o default do coletor
    web:
      exposure:
        #include: 'health,metrics,prometheus'
        include: '*' # mostra dos os endpoints que pertencem ao actuator só sera visiveis com o  enabled-by-default: true
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

logging:
  file:
    name: logs/address-service.log
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

server:
  port: 8080

client:
  viaCep:
    uri: https://viacep.com.br/ws/
