spring:
  application:
    name: address-reactive-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/address

management:
  tracing:
    sampling:
      probability: 1

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

server:
  port: 8080